// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_alignedtoline_per_layer_loop3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        points_address0,
        points_ce0,
        points_q0,
        points_address1,
        points_ce1,
        points_q1,
        num_points_address0,
        num_points_ce0,
        num_points_q0,
        num_points_address1,
        num_points_ce1,
        num_points_q1,
        init_patch_address0,
        init_patch_ce0,
        init_patch_we0,
        init_patch_d0,
        init_patch_address1,
        init_patch_ce1,
        init_patch_we1,
        init_patch_d1,
        i_offset
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] points_address0;
output   points_ce0;
input  [127:0] points_q0;
output  [11:0] points_address1;
output   points_ce1;
input  [127:0] points_q1;
output  [2:0] num_points_address0;
output   num_points_ce0;
input  [31:0] num_points_q0;
output  [2:0] num_points_address1;
output   num_points_ce1;
input  [31:0] num_points_q1;
output  [6:0] init_patch_address0;
output   init_patch_ce0;
output   init_patch_we0;
output  [95:0] init_patch_d0;
output  [6:0] init_patch_address1;
output   init_patch_ce1;
output   init_patch_we1;
output  [95:0] init_patch_d1;
input  [2:0] i_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] points_address0;
reg points_ce0;
reg[11:0] points_address1;
reg points_ce1;
reg[2:0] num_points_address0;
reg num_points_ce0;
reg num_points_ce1;
reg[6:0] init_patch_address0;
reg init_patch_ce0;
reg init_patch_we0;
reg[95:0] init_patch_d0;
reg[6:0] init_patch_address1;
reg init_patch_ce1;
reg init_patch_we1;
reg[95:0] init_patch_d1;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] get_radiiradii_address0;
reg    get_radiiradii_ce0;
wire   [31:0] get_radiiradii_q0;
reg   [31:0] lbVal_constprop;
reg   [31:0] rbVal_constprop;
wire   [63:0] zext_ln84_fu_573_p1;
reg   [63:0] zext_ln84_reg_2191;
wire   [69:0] mul_ln1148_fu_627_p2;
reg   [69:0] mul_ln1148_reg_2201;
wire    ap_CS_fsm_state2;
reg   [25:0] projectionToRow_V_reg_2206;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
reg   [6:0] init_patch_addr_reg_2217;
wire    ap_CS_fsm_state6;
reg   [6:0] init_patch_addr_1_reg_2222;
reg   [6:0] init_patch_addr_2_reg_2227;
reg   [6:0] init_patch_addr_3_reg_2232;
reg   [6:0] init_patch_addr_4_reg_2237;
reg   [6:0] init_patch_addr_5_reg_2242;
reg   [6:0] init_patch_addr_6_reg_2247;
reg   [6:0] init_patch_addr_7_reg_2252;
reg   [6:0] init_patch_addr_8_reg_2257;
reg   [6:0] init_patch_addr_9_reg_2262;
reg   [6:0] init_patch_addr_10_reg_2267;
reg   [6:0] init_patch_addr_11_reg_2272;
reg   [6:0] init_patch_addr_12_reg_2277;
reg   [6:0] init_patch_addr_13_reg_2282;
reg   [6:0] init_patch_addr_14_reg_2287;
reg   [6:0] init_patch_addr_15_reg_2292;
wire   [31:0] zext_ln708_fu_906_p1;
reg   [31:0] zext_ln708_reg_2297;
wire   [0:0] icmp_ln874_fu_918_p2;
reg   [0:0] icmp_ln874_reg_2305;
wire   [0:0] icmp_ln885_fu_927_p2;
reg   [0:0] icmp_ln885_reg_2309;
wire   [0:0] p_Result_4_fu_933_p3;
reg   [0:0] p_Result_4_reg_2313;
wire   [31:0] m_5_fu_947_p3;
reg   [31:0] m_5_reg_2318;
wire   [31:0] sub_ln894_fu_973_p2;
reg   [31:0] sub_ln894_reg_2323;
wire   [0:0] icmp_ln908_fu_1067_p2;
reg   [0:0] icmp_ln908_reg_2329;
wire   [0:0] select_ln908_fu_1087_p3;
reg   [0:0] select_ln908_reg_2334;
wire   [10:0] trunc_ln893_fu_1095_p1;
reg   [10:0] trunc_ln893_reg_2339;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln1506_fu_1223_p2;
reg   [0:0] icmp_ln1506_reg_2349;
wire   [0:0] icmp_ln1506_1_fu_1229_p2;
reg   [0:0] icmp_ln1506_1_reg_2354;
wire   [0:0] and_ln1506_fu_1239_p2;
reg   [0:0] and_ln1506_reg_2359;
wire    ap_CS_fsm_state8;
wire   [11:0] ret_16_fu_1324_p1;
reg   [11:0] ret_16_reg_2368;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln878_fu_1341_p2;
reg   [0:0] icmp_ln878_reg_2386;
wire   [8:0] trunc_ln1461_fu_1347_p1;
reg   [8:0] trunc_ln1461_reg_2390;
wire   [15:0] shl_ln1_fu_1357_p3;
reg   [15:0] shl_ln1_reg_2408;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg   [2:0] lshr_ln198_8_reg_2466;
reg   [2:0] lshr_ln198_9_reg_2471;
reg   [2:0] lshr_ln198_s_reg_2476;
reg   [2:0] lshr_ln198_10_reg_2481;
reg   [2:0] lshr_ln198_11_reg_2486;
reg   [2:0] lshr_ln198_12_reg_2491;
reg   [2:0] lshr_ln198_13_reg_2496;
reg   [2:0] lshr_ln198_14_reg_2501;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire   [2:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address0;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce0;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_d0;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_we0;
wire   [2:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address1;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce1;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_d1;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_we1;
wire   [11:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address0;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce0;
wire   [127:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_d0;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_we0;
wire   [11:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address1;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce1;
wire   [127:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_d1;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_we1;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o;
wire   [31:0] grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound_ap_vld;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o_ap_vld;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o_ap_vld;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index_ap_vld;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o_ap_vld;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready;
wire    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_idle;
reg    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_continue;
wire   [31:0] start_index_V_1_fu_1299_p2;
reg  signed [31:0] ap_phi_mux_lhs_1_phi_fu_539_p8;
reg  signed [31:0] lhs_1_reg_536;
reg    grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready;
wire    ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done;
reg    ap_block_state4_on_subcall_done;
reg    ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready;
reg    ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done;
reg   [31:0] left_bound_V_fu_234;
reg   [31:0] start_index_V_fu_226;
reg   [31:0] start_value_V_fu_230;
wire   [63:0] zext_ln206_fu_676_p1;
wire   [63:0] tmp_3_fu_687_p3;
wire   [63:0] tmp_4_fu_702_p3;
wire   [63:0] tmp_5_fu_717_p3;
wire   [63:0] tmp_6_fu_732_p3;
wire   [63:0] tmp_7_fu_747_p3;
wire   [63:0] tmp_8_fu_762_p3;
wire   [63:0] tmp_9_fu_777_p3;
wire   [63:0] tmp_s_fu_792_p3;
wire   [63:0] tmp_10_fu_807_p3;
wire   [63:0] tmp_11_fu_822_p3;
wire   [63:0] tmp_12_fu_837_p3;
wire   [63:0] tmp_13_fu_852_p3;
wire   [63:0] tmp_14_fu_867_p3;
wire   [63:0] tmp_15_fu_882_p3;
wire   [63:0] tmp_16_fu_897_p3;
wire   [63:0] zext_ln174_fu_1290_p1;
wire   [63:0] zext_ln198_fu_1402_p1;
wire   [63:0] zext_ln198_1_fu_1451_p1;
wire   [63:0] zext_ln198_2_fu_1507_p1;
wire   [63:0] zext_ln198_3_fu_1553_p1;
wire   [63:0] zext_ln198_4_fu_1609_p1;
wire   [63:0] zext_ln198_5_fu_1655_p1;
wire   [63:0] zext_ln198_6_fu_1711_p1;
wire   [63:0] zext_ln198_7_fu_1757_p1;
wire   [63:0] zext_ln198_8_fu_2002_p1;
wire   [63:0] zext_ln198_9_fu_2019_p1;
wire   [63:0] zext_ln198_10_fu_2046_p1;
wire   [63:0] zext_ln198_11_fu_2063_p1;
wire   [63:0] zext_ln198_12_fu_2090_p1;
wire   [63:0] zext_ln198_13_fu_2107_p1;
wire   [63:0] zext_ln198_14_fu_2134_p1;
wire   [63:0] zext_ln198_15_fu_2145_p1;
wire   [31:0] start_value_V_1_fu_1310_p2;
wire   [95:0] temp_superpoint_V_fu_1456_p1;
wire   [95:0] temp_superpoint_V_1_fu_1461_p1;
wire   [95:0] temp_superpoint_V_2_fu_1558_p1;
wire   [95:0] temp_superpoint_V_3_fu_1563_p1;
wire   [95:0] temp_superpoint_V_4_fu_1660_p1;
wire   [95:0] temp_superpoint_V_5_fu_1665_p1;
wire   [95:0] temp_superpoint_V_6_fu_1980_p1;
wire   [95:0] temp_superpoint_V_7_fu_1985_p1;
wire   [95:0] temp_superpoint_V_8_fu_2024_p1;
wire   [95:0] temp_superpoint_V_9_fu_2029_p1;
wire   [95:0] temp_superpoint_V_10_fu_2068_p1;
wire   [95:0] temp_superpoint_V_11_fu_2073_p1;
wire   [95:0] temp_superpoint_V_12_fu_2112_p1;
wire   [95:0] temp_superpoint_V_13_fu_2117_p1;
wire    ap_CS_fsm_state17;
wire   [95:0] temp_superpoint_V_14_fu_2150_p1;
wire   [95:0] temp_superpoint_V_15_fu_2155_p1;
wire   [63:0] grp_fu_568_p0;
wire   [4:0] trunc_ln731_fu_605_p1;
wire   [24:0] y_V_fu_609_p3;
wire   [24:0] ret_V_fu_617_p2;
wire   [24:0] mul_ln1148_fu_627_p0;
wire   [45:0] mul_ln1148_fu_627_p1;
wire   [69:0] mul_ln1148_1_fu_636_p0;
wire   [71:0] mul_ln1148_1_fu_636_p1;
wire   [140:0] mul_ln1148_1_fu_636_p2;
wire   [45:0] trunc_ln_fu_642_p4;
wire   [45:0] ret_V_1_fu_652_p2;
wire   [6:0] tmp_fu_669_p3;
wire   [6:0] or_ln206_fu_681_p2;
wire   [6:0] or_ln206_1_fu_696_p2;
wire   [6:0] or_ln206_2_fu_711_p2;
wire   [6:0] or_ln206_3_fu_726_p2;
wire   [6:0] or_ln206_4_fu_741_p2;
wire   [6:0] or_ln206_5_fu_756_p2;
wire   [6:0] or_ln206_6_fu_771_p2;
wire   [6:0] or_ln206_7_fu_786_p2;
wire   [6:0] or_ln206_8_fu_801_p2;
wire   [6:0] or_ln206_9_fu_816_p2;
wire   [6:0] or_ln206_10_fu_831_p2;
wire   [6:0] or_ln206_11_fu_846_p2;
wire   [6:0] or_ln206_12_fu_861_p2;
wire   [6:0] or_ln206_13_fu_876_p2;
wire   [6:0] or_ln206_14_fu_891_p2;
wire   [31:0] add_ln167_fu_909_p2;
wire   [31:0] tmp_V_fu_941_p2;
reg   [31:0] p_Result_5_fu_955_p4;
reg   [31:0] l_fu_965_p3;
wire   [31:0] lsb_index_fu_979_p2;
wire   [30:0] tmp_19_fu_985_p4;
wire   [5:0] trunc_ln897_fu_1001_p1;
wire   [5:0] sub_ln897_fu_1005_p2;
wire   [31:0] zext_ln897_fu_1011_p1;
wire   [31:0] lshr_ln897_fu_1015_p2;
wire   [31:0] shl_ln899_fu_1021_p2;
wire   [31:0] or_ln899_1_fu_1027_p2;
wire   [31:0] and_ln899_fu_1033_p2;
wire   [0:0] tmp_20_fu_1045_p3;
wire   [0:0] p_Result_6_fu_1059_p3;
wire   [0:0] xor_ln899_fu_1053_p2;
wire   [0:0] icmp_ln896_fu_995_p2;
wire   [0:0] icmp_ln899_fu_1039_p2;
wire   [0:0] select_ln896_fu_1079_p3;
wire   [0:0] and_ln899_1_fu_1073_p2;
wire   [31:0] sub_ln909_fu_1102_p2;
wire   [63:0] zext_ln909_1_fu_1099_p1;
wire   [63:0] zext_ln909_fu_1107_p1;
wire   [31:0] add_ln908_fu_1117_p2;
wire   [63:0] zext_ln908_fu_1122_p1;
wire   [63:0] lshr_ln908_fu_1126_p2;
wire   [63:0] shl_ln909_fu_1111_p2;
wire   [63:0] m_fu_1132_p3;
wire   [63:0] zext_ln911_fu_1139_p1;
wire   [63:0] m_2_fu_1142_p2;
wire   [62:0] m_6_fu_1148_p4;
wire   [0:0] p_Result_s_fu_1162_p3;
wire   [10:0] sub_ln915_fu_1178_p2;
wire   [10:0] select_ln893_fu_1170_p3;
wire   [10:0] add_ln915_fu_1183_p2;
wire   [63:0] zext_ln912_fu_1158_p1;
wire   [11:0] tmp_1_fu_1189_p3;
wire   [63:0] p_Result_7_fu_1196_p5;
wire   [51:0] trunc_ln3_fu_1213_p4;
wire   [0:0] or_ln1506_fu_1235_p2;
wire   [0:0] grp_fu_568_p2;
wire   [11:0] trunc_ln174_fu_1252_p1;
wire   [15:0] shl_ln174_1_fu_1255_p3;
wire   [15:0] shl_ln_fu_1245_p3;
wire   [15:0] add_ln174_fu_1263_p2;
wire   [2:0] lshr_ln_fu_1269_p4;
wire   [8:0] trunc_ln174_1_fu_1279_p1;
wire   [11:0] tmp_18_fu_1282_p3;
wire   [31:0] z_bits_fu_1295_p1;
wire  signed [32:0] sext_ln215_fu_1320_p1;
wire   [32:0] ret_fu_1328_p2;
wire  signed [32:0] sext_ln878_fu_1337_p1;
wire   [11:0] add_ln1461_fu_1351_p2;
wire   [15:0] shl_ln198_1_fu_1364_p3;
wire   [15:0] add_ln198_fu_1372_p2;
wire   [2:0] lshr_ln1_fu_1378_p4;
wire   [8:0] add_ln198_16_fu_1388_p2;
wire   [11:0] tmp_21_fu_1394_p3;
wire   [11:0] ret_2_fu_1407_p2;
wire   [15:0] shl_ln198_2_fu_1413_p3;
wire   [15:0] add_ln198_1_fu_1421_p2;
wire   [2:0] lshr_ln198_1_fu_1427_p4;
wire   [8:0] add_ln198_17_fu_1437_p2;
wire   [11:0] tmp_22_fu_1443_p3;
wire   [11:0] ret_3_fu_1466_p2;
wire   [15:0] shl_ln198_3_fu_1471_p3;
wire   [15:0] add_ln198_2_fu_1479_p2;
wire   [2:0] lshr_ln198_2_fu_1484_p4;
wire   [8:0] add_ln198_18_fu_1494_p2;
wire   [11:0] tmp_23_fu_1499_p3;
wire   [11:0] ret_4_fu_1512_p2;
wire   [15:0] shl_ln198_4_fu_1517_p3;
wire   [15:0] add_ln198_3_fu_1525_p2;
wire   [2:0] lshr_ln198_3_fu_1530_p4;
wire   [8:0] add_ln198_19_fu_1540_p2;
wire   [11:0] tmp_24_fu_1545_p3;
wire   [11:0] ret_5_fu_1568_p2;
wire   [15:0] shl_ln198_5_fu_1573_p3;
wire   [15:0] add_ln198_4_fu_1581_p2;
wire   [2:0] lshr_ln198_4_fu_1586_p4;
wire   [8:0] add_ln198_20_fu_1596_p2;
wire   [11:0] tmp_25_fu_1601_p3;
wire   [11:0] ret_6_fu_1614_p2;
wire   [15:0] shl_ln198_6_fu_1619_p3;
wire   [15:0] add_ln198_5_fu_1627_p2;
wire   [2:0] lshr_ln198_5_fu_1632_p4;
wire   [8:0] add_ln198_21_fu_1642_p2;
wire   [11:0] tmp_26_fu_1647_p3;
wire   [11:0] ret_7_fu_1670_p2;
wire   [15:0] shl_ln198_7_fu_1675_p3;
wire   [15:0] add_ln198_6_fu_1683_p2;
wire   [2:0] lshr_ln198_6_fu_1688_p4;
wire   [8:0] add_ln198_22_fu_1698_p2;
wire   [11:0] tmp_27_fu_1703_p3;
wire   [11:0] ret_8_fu_1716_p2;
wire   [15:0] shl_ln198_8_fu_1721_p3;
wire   [15:0] add_ln198_7_fu_1729_p2;
wire   [2:0] lshr_ln198_7_fu_1734_p4;
wire   [8:0] add_ln198_23_fu_1744_p2;
wire   [11:0] tmp_28_fu_1749_p3;
wire   [11:0] ret_9_fu_1762_p2;
wire   [15:0] shl_ln198_9_fu_1767_p3;
wire   [15:0] add_ln198_8_fu_1775_p2;
wire   [11:0] ret_10_fu_1790_p2;
wire   [15:0] shl_ln198_s_fu_1795_p3;
wire   [15:0] add_ln198_9_fu_1803_p2;
wire   [11:0] ret_11_fu_1818_p2;
wire   [15:0] shl_ln198_10_fu_1823_p3;
wire   [15:0] add_ln198_10_fu_1831_p2;
wire   [11:0] ret_12_fu_1846_p2;
wire   [15:0] shl_ln198_11_fu_1851_p3;
wire   [15:0] add_ln198_11_fu_1859_p2;
wire   [11:0] ret_13_fu_1874_p2;
wire   [15:0] shl_ln198_12_fu_1879_p3;
wire   [15:0] add_ln198_12_fu_1887_p2;
wire   [11:0] ret_14_fu_1902_p2;
wire   [15:0] shl_ln198_13_fu_1907_p3;
wire   [15:0] add_ln198_13_fu_1915_p2;
wire   [11:0] ret_15_fu_1930_p2;
wire   [15:0] shl_ln198_14_fu_1935_p3;
wire   [15:0] add_ln198_14_fu_1943_p2;
wire   [15:0] shl_ln198_15_fu_1958_p3;
wire   [15:0] add_ln198_15_fu_1965_p2;
wire   [8:0] add_ln198_24_fu_1990_p2;
wire   [11:0] tmp_29_fu_1995_p3;
wire   [8:0] add_ln198_25_fu_2007_p2;
wire   [11:0] tmp_30_fu_2012_p3;
wire   [8:0] add_ln198_26_fu_2034_p2;
wire   [11:0] tmp_31_fu_2039_p3;
wire   [8:0] add_ln198_27_fu_2051_p2;
wire   [11:0] tmp_32_fu_2056_p3;
wire   [8:0] add_ln198_28_fu_2078_p2;
wire   [11:0] tmp_33_fu_2083_p3;
wire   [8:0] add_ln198_29_fu_2095_p2;
wire   [11:0] tmp_34_fu_2100_p3;
wire   [8:0] add_ln198_30_fu_2122_p2;
wire   [11:0] tmp_35_fu_2127_p3;
wire   [11:0] tmp_36_fu_2139_p3;
reg   [16:0] ap_NS_fsm;
wire   [140:0] mul_ln1148_1_fu_636_p00;
wire   [69:0] mul_ln1148_fu_627_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 lbVal_constprop = 32'd1073741824;
#0 rbVal_constprop = 32'd1073741824;
#0 grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready = 1'b0;
#0 ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done = 1'b0;
end

system_top_alignedtoline_per_layer_loop3_get_radiiradii #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
get_radiiradii_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(get_radiiradii_address0),
    .ce0(get_radiiradii_ce0),
    .q0(get_radiiradii_q0)
);

system_top_p_find_boundaries_and_starting_index_and_value4 grp_p_find_boundaries_and_starting_index_and_value4_fu_549(
    .num_points_address0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address0),
    .num_points_ce0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce0),
    .num_points_d0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_d0),
    .num_points_q0(num_points_q0),
    .num_points_we0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_we0),
    .num_points_address1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address1),
    .num_points_ce1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce1),
    .num_points_d1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_d1),
    .num_points_q1(num_points_q1),
    .num_points_we1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_we1),
    .points_address0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address0),
    .points_ce0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce0),
    .points_d0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_d0),
    .points_q0(points_q0),
    .points_we0(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_we0),
    .points_address1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address1),
    .points_ce1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce1),
    .points_d1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_d1),
    .points_q1(points_q1),
    .points_we1(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_we1),
    .left_bound(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound),
    .projectionToRow(projectionToRow_V_reg_2206),
    .start_index(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index),
    .start_value_i(start_value_V_fu_230),
    .start_value_o(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o),
    .i(i_offset),
    .lbVal_constprop_i(lbVal_constprop),
    .lbVal_constprop_o(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o),
    .rbVal_constprop_i(rbVal_constprop),
    .rbVal_constprop_o(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .projectionToRow_ap_vld(1'b1),
    .i_ap_vld(1'b1),
    .ap_start(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start),
    .left_bound_ap_vld(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound_ap_vld),
    .lbVal_constprop_i_ap_vld(1'b1),
    .lbVal_constprop_o_ap_vld(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o_ap_vld),
    .rbVal_constprop_i_ap_vld(1'b1),
    .rbVal_constprop_o_ap_vld(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o_ap_vld),
    .ap_done(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done),
    .start_index_ap_vld(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index_ap_vld),
    .start_value_i_ap_vld(1'b1),
    .start_value_o_ap_vld(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o_ap_vld),
    .ap_ready(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready),
    .ap_idle(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_idle),
    .ap_continue(grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_continue)
);

system_top_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_568_p0),
    .din1(64'd13755392620465711345),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_568_p2)
);

system_top_mul_25ns_46ns_70_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 46 ),
    .dout_WIDTH( 70 ))
mul_25ns_46ns_70_1_1_U43(
    .din0(mul_ln1148_fu_627_p0),
    .din1(mul_ln1148_fu_627_p1),
    .dout(mul_ln1148_fu_627_p2)
);

system_top_mul_70ns_72ns_141_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 70 ),
    .din1_WIDTH( 72 ),
    .dout_WIDTH( 141 ))
mul_70ns_72ns_141_1_1_U44(
    .din0(mul_ln1148_1_fu_636_p0),
    .din1(mul_ln1148_1_fu_636_p1),
    .dout(mul_ln1148_1_fu_636_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done <= 1'b0;
        end else if ((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done == 1'b1)) begin
            ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready <= 1'b0;
        end else if ((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg <= 1'b1;
        end else if ((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready == 1'b1)) begin
            grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        lbVal_constprop <= 32'd1073741824;
    end else if (((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        lbVal_constprop <= grp_p_find_boundaries_and_starting_index_and_value4_fu_549_lbVal_constprop_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        left_bound_V_fu_234 <= 32'd0;
    end else if (((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        left_bound_V_fu_234 <= grp_p_find_boundaries_and_starting_index_and_value4_fu_549_left_bound;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state8) & (1'd0 == and_ln1506_fu_1239_p2)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln885_fu_927_p2 == 1'd1) & (icmp_ln874_fu_918_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln874_fu_918_p2 == 1'd1)))) begin
        lhs_1_reg_536 <= start_index_V_fu_226;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln1506_reg_2359) & (icmp_ln885_reg_2309 == 1'd0) & (icmp_ln874_reg_2305 == 1'd0))) begin
        lhs_1_reg_536 <= start_index_V_1_fu_1299_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        rbVal_constprop <= 32'd1073741824;
    end else if (((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rbVal_constprop <= grp_p_find_boundaries_and_starting_index_and_value4_fu_549_rbVal_constprop_o;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        start_index_V_fu_226 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln1506_reg_2359) & (icmp_ln885_reg_2309 == 1'd0) & (icmp_ln874_reg_2305 == 1'd0))) begin
        start_index_V_fu_226 <= start_index_V_1_fu_1299_p2;
    end else if (((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        start_index_V_fu_226 <= grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_index;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        start_value_V_fu_230 <= 32'd1073741824;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln1506_reg_2359) & (icmp_ln885_reg_2309 == 1'd0) & (icmp_ln874_reg_2305 == 1'd0))) begin
        start_value_V_fu_230 <= start_value_V_1_fu_1310_p2;
    end else if (((grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        start_value_V_fu_230 <= grp_p_find_boundaries_and_starting_index_and_value4_fu_549_start_value_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        and_ln1506_reg_2359 <= and_ln1506_fu_1239_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln1506_1_reg_2354 <= icmp_ln1506_1_fu_1229_p2;
        icmp_ln1506_reg_2349 <= icmp_ln1506_fu_1223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln874_reg_2305 <= icmp_ln874_fu_918_p2;
        init_patch_addr_10_reg_2267[6 : 4] <= tmp_11_fu_822_p3[6 : 4];
        init_patch_addr_11_reg_2272[6 : 4] <= tmp_12_fu_837_p3[6 : 4];
        init_patch_addr_12_reg_2277[6 : 4] <= tmp_13_fu_852_p3[6 : 4];
        init_patch_addr_13_reg_2282[6 : 4] <= tmp_14_fu_867_p3[6 : 4];
        init_patch_addr_14_reg_2287[6 : 4] <= tmp_15_fu_882_p3[6 : 4];
        init_patch_addr_15_reg_2292[6 : 4] <= tmp_16_fu_897_p3[6 : 4];
        init_patch_addr_1_reg_2222[6 : 4] <= tmp_3_fu_687_p3[6 : 4];
        init_patch_addr_2_reg_2227[6 : 4] <= tmp_4_fu_702_p3[6 : 4];
        init_patch_addr_3_reg_2232[6 : 4] <= tmp_5_fu_717_p3[6 : 4];
        init_patch_addr_4_reg_2237[6 : 4] <= tmp_6_fu_732_p3[6 : 4];
        init_patch_addr_5_reg_2242[6 : 4] <= tmp_7_fu_747_p3[6 : 4];
        init_patch_addr_6_reg_2247[6 : 4] <= tmp_8_fu_762_p3[6 : 4];
        init_patch_addr_7_reg_2252[6 : 4] <= tmp_9_fu_777_p3[6 : 4];
        init_patch_addr_8_reg_2257[6 : 4] <= tmp_s_fu_792_p3[6 : 4];
        init_patch_addr_9_reg_2262[6 : 4] <= tmp_10_fu_807_p3[6 : 4];
        init_patch_addr_reg_2217[6 : 4] <= zext_ln206_fu_676_p1[6 : 4];
        zext_ln708_reg_2297[25 : 0] <= zext_ln708_fu_906_p1[25 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln878_reg_2386 <= icmp_ln878_fu_1341_p2;
        ret_16_reg_2368 <= ret_16_fu_1324_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln874_fu_918_p2 == 1'd0))) begin
        icmp_ln885_reg_2309 <= icmp_ln885_fu_927_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln885_fu_927_p2 == 1'd0) & (icmp_ln874_fu_918_p2 == 1'd0))) begin
        icmp_ln908_reg_2329 <= icmp_ln908_fu_1067_p2;
        m_5_reg_2318 <= m_5_fu_947_p3;
        p_Result_4_reg_2313 <= start_value_V_fu_230[32'd31];
        select_ln908_reg_2334 <= select_ln908_fu_1087_p3;
        sub_ln894_reg_2323 <= sub_ln894_fu_973_p2;
        trunc_ln893_reg_2339 <= trunc_ln893_fu_1095_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        lshr_ln198_10_reg_2481 <= {{add_ln198_11_fu_1859_p2[15:13]}};
        lshr_ln198_11_reg_2486 <= {{add_ln198_12_fu_1887_p2[15:13]}};
        lshr_ln198_12_reg_2491 <= {{add_ln198_13_fu_1915_p2[15:13]}};
        lshr_ln198_13_reg_2496 <= {{add_ln198_14_fu_1943_p2[15:13]}};
        lshr_ln198_14_reg_2501 <= {{add_ln198_15_fu_1965_p2[15:13]}};
        lshr_ln198_8_reg_2466 <= {{add_ln198_8_fu_1775_p2[15:13]}};
        lshr_ln198_9_reg_2471 <= {{add_ln198_9_fu_1803_p2[15:13]}};
        lshr_ln198_s_reg_2476 <= {{add_ln198_10_fu_1831_p2[15:13]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln1148_reg_2201 <= mul_ln1148_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        projectionToRow_V_reg_2206 <= {{ret_V_1_fu_652_p2[45:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln878_fu_1341_p2 == 1'd0))) begin
        shl_ln1_reg_2408[15 : 13] <= shl_ln1_fu_1357_p3[15 : 13];
        trunc_ln1461_reg_2390 <= trunc_ln1461_fu_1347_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        zext_ln84_reg_2191[2 : 0] <= zext_ln84_fu_573_p1[2 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (1'd1 == and_ln1506_reg_2359) & (icmp_ln885_reg_2309 == 1'd0) & (icmp_ln874_reg_2305 == 1'd0))) begin
        ap_phi_mux_lhs_1_phi_fu_539_p8 = start_index_V_1_fu_1299_p2;
    end else begin
        ap_phi_mux_lhs_1_phi_fu_539_p8 = lhs_1_reg_536;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        get_radiiradii_ce0 = 1'b1;
    end else begin
        get_radiiradii_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_continue = 1'b1;
    end else begin
        grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        init_patch_address0 = init_patch_addr_15_reg_2292;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        init_patch_address0 = init_patch_addr_13_reg_2282;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        init_patch_address0 = init_patch_addr_11_reg_2272;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        init_patch_address0 = init_patch_addr_9_reg_2262;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        init_patch_address0 = init_patch_addr_7_reg_2252;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        init_patch_address0 = init_patch_addr_5_reg_2242;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        init_patch_address0 = init_patch_addr_3_reg_2232;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        init_patch_address0 = init_patch_addr_1_reg_2222;
    end else begin
        init_patch_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        init_patch_address1 = init_patch_addr_14_reg_2287;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        init_patch_address1 = init_patch_addr_12_reg_2277;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        init_patch_address1 = init_patch_addr_10_reg_2267;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        init_patch_address1 = init_patch_addr_8_reg_2257;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        init_patch_address1 = init_patch_addr_6_reg_2247;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        init_patch_address1 = init_patch_addr_4_reg_2237;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        init_patch_address1 = init_patch_addr_2_reg_2227;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        init_patch_address1 = init_patch_addr_reg_2217;
    end else begin
        init_patch_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        init_patch_ce0 = 1'b1;
    end else begin
        init_patch_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        init_patch_ce1 = 1'b1;
    end else begin
        init_patch_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        init_patch_d0 = temp_superpoint_V_15_fu_2155_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        init_patch_d0 = temp_superpoint_V_13_fu_2117_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        init_patch_d0 = temp_superpoint_V_11_fu_2073_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        init_patch_d0 = temp_superpoint_V_9_fu_2029_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        init_patch_d0 = temp_superpoint_V_7_fu_1985_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        init_patch_d0 = temp_superpoint_V_5_fu_1665_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        init_patch_d0 = temp_superpoint_V_3_fu_1563_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        init_patch_d0 = temp_superpoint_V_1_fu_1461_p1;
    end else begin
        init_patch_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        init_patch_d1 = temp_superpoint_V_14_fu_2150_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        init_patch_d1 = temp_superpoint_V_12_fu_2112_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        init_patch_d1 = temp_superpoint_V_10_fu_2068_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        init_patch_d1 = temp_superpoint_V_8_fu_2024_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        init_patch_d1 = temp_superpoint_V_6_fu_1980_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        init_patch_d1 = temp_superpoint_V_4_fu_1660_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        init_patch_d1 = temp_superpoint_V_2_fu_1558_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        init_patch_d1 = temp_superpoint_V_fu_1456_p1;
    end else begin
        init_patch_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state17) & (icmp_ln878_reg_2386 == 1'd0)))) begin
        init_patch_we0 = 1'b1;
    end else begin
        init_patch_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state17) & (icmp_ln878_reg_2386 == 1'd0)))) begin
        init_patch_we1 = 1'b1;
    end else begin
        init_patch_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        num_points_address0 = zext_ln84_reg_2191;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        num_points_address0 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address0;
    end else begin
        num_points_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        num_points_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        num_points_ce0 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce0;
    end else begin
        num_points_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        num_points_ce1 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_ce1;
    end else begin
        num_points_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        points_address0 = zext_ln198_14_fu_2134_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        points_address0 = zext_ln198_12_fu_2090_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        points_address0 = zext_ln198_10_fu_2046_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        points_address0 = zext_ln198_8_fu_2002_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        points_address0 = zext_ln198_6_fu_1711_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        points_address0 = zext_ln198_4_fu_1609_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        points_address0 = zext_ln198_2_fu_1507_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        points_address0 = zext_ln198_1_fu_1451_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        points_address0 = zext_ln174_fu_1290_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        points_address0 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address0;
    end else begin
        points_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        points_address1 = zext_ln198_15_fu_2145_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        points_address1 = zext_ln198_13_fu_2107_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        points_address1 = zext_ln198_11_fu_2063_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        points_address1 = zext_ln198_9_fu_2019_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        points_address1 = zext_ln198_7_fu_1757_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        points_address1 = zext_ln198_5_fu_1655_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        points_address1 = zext_ln198_3_fu_1553_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        points_address1 = zext_ln198_fu_1402_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        points_address1 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_address1;
    end else begin
        points_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        points_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        points_ce0 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce0;
    end else begin
        points_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        points_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        points_ce1 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_points_ce1;
    end else begin
        points_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln885_fu_927_p2 == 1'd0) & (icmp_ln874_fu_918_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln878_fu_1341_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1461_fu_1351_p2 = ($signed(ret_16_fu_1324_p1) + $signed(12'd4081));

assign add_ln167_fu_909_p2 = ($signed(num_points_q0) + $signed(32'd4294967295));

assign add_ln174_fu_1263_p2 = (shl_ln174_1_fu_1255_p3 + shl_ln_fu_1245_p3);

assign add_ln198_10_fu_1831_p2 = (shl_ln198_10_fu_1823_p3 + shl_ln1_reg_2408);

assign add_ln198_11_fu_1859_p2 = (shl_ln198_11_fu_1851_p3 + shl_ln1_reg_2408);

assign add_ln198_12_fu_1887_p2 = (shl_ln198_12_fu_1879_p3 + shl_ln1_reg_2408);

assign add_ln198_13_fu_1915_p2 = (shl_ln198_13_fu_1907_p3 + shl_ln1_reg_2408);

assign add_ln198_14_fu_1943_p2 = (shl_ln198_14_fu_1935_p3 + shl_ln1_reg_2408);

assign add_ln198_15_fu_1965_p2 = (shl_ln198_15_fu_1958_p3 + shl_ln1_reg_2408);

assign add_ln198_16_fu_1388_p2 = ($signed(trunc_ln1461_fu_1347_p1) + $signed(9'd497));

assign add_ln198_17_fu_1437_p2 = ($signed(trunc_ln1461_fu_1347_p1) + $signed(9'd498));

assign add_ln198_18_fu_1494_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd499));

assign add_ln198_19_fu_1540_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd500));

assign add_ln198_1_fu_1421_p2 = (shl_ln198_2_fu_1413_p3 + shl_ln1_fu_1357_p3);

assign add_ln198_20_fu_1596_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd501));

assign add_ln198_21_fu_1642_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd502));

assign add_ln198_22_fu_1698_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd503));

assign add_ln198_23_fu_1744_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd504));

assign add_ln198_24_fu_1990_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd505));

assign add_ln198_25_fu_2007_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd506));

assign add_ln198_26_fu_2034_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd507));

assign add_ln198_27_fu_2051_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd508));

assign add_ln198_28_fu_2078_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd509));

assign add_ln198_29_fu_2095_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd510));

assign add_ln198_2_fu_1479_p2 = (shl_ln198_3_fu_1471_p3 + shl_ln1_reg_2408);

assign add_ln198_30_fu_2122_p2 = ($signed(trunc_ln1461_reg_2390) + $signed(9'd511));

assign add_ln198_3_fu_1525_p2 = (shl_ln198_4_fu_1517_p3 + shl_ln1_reg_2408);

assign add_ln198_4_fu_1581_p2 = (shl_ln198_5_fu_1573_p3 + shl_ln1_reg_2408);

assign add_ln198_5_fu_1627_p2 = (shl_ln198_6_fu_1619_p3 + shl_ln1_reg_2408);

assign add_ln198_6_fu_1683_p2 = (shl_ln198_7_fu_1675_p3 + shl_ln1_reg_2408);

assign add_ln198_7_fu_1729_p2 = (shl_ln198_8_fu_1721_p3 + shl_ln1_reg_2408);

assign add_ln198_8_fu_1775_p2 = (shl_ln198_9_fu_1767_p3 + shl_ln1_reg_2408);

assign add_ln198_9_fu_1803_p2 = (shl_ln198_s_fu_1795_p3 + shl_ln1_reg_2408);

assign add_ln198_fu_1372_p2 = (shl_ln198_1_fu_1364_p3 + shl_ln1_fu_1357_p3);

assign add_ln908_fu_1117_p2 = ($signed(sub_ln894_reg_2323) + $signed(32'd4294967242));

assign add_ln915_fu_1183_p2 = (sub_ln915_fu_1178_p2 + select_ln893_fu_1170_p3);

assign and_ln1506_fu_1239_p2 = (or_ln1506_fu_1235_p2 & grp_fu_568_p2);

assign and_ln899_1_fu_1073_p2 = (xor_ln899_fu_1053_p2 & p_Result_6_fu_1059_p3);

assign and_ln899_fu_1033_p2 = (or_ln899_1_fu_1027_p2 & m_5_fu_947_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready & ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done) == 1'b0);
end

assign ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done = (grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done | ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_done);

assign ap_sync_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready = (grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready | ap_sync_reg_grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_ready);

assign get_radiiradii_address0 = zext_ln84_fu_573_p1;

assign grp_fu_568_p0 = p_Result_7_fu_1196_p5;

assign grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_ap_start_reg;

assign icmp_ln1506_1_fu_1229_p2 = ((trunc_ln3_fu_1213_p4 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln1506_fu_1223_p2 = ((add_ln915_fu_1183_p2 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln874_fu_918_p2 = ((start_index_V_fu_226 == add_ln167_fu_909_p2) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_1341_p2 = (($signed(ret_fu_1328_p2) < $signed(sext_ln878_fu_1337_p1)) ? 1'b1 : 1'b0);

assign icmp_ln885_fu_927_p2 = ((start_value_V_fu_230 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln896_fu_995_p2 = (($signed(tmp_19_fu_985_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_1039_p2 = ((and_ln899_fu_1033_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln908_fu_1067_p2 = (($signed(lsb_index_fu_979_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);


always @ (p_Result_5_fu_955_p4) begin
    if (p_Result_5_fu_955_p4[0] == 1'b1) begin
        l_fu_965_p3 = 32'd0;
    end else if (p_Result_5_fu_955_p4[1] == 1'b1) begin
        l_fu_965_p3 = 32'd1;
    end else if (p_Result_5_fu_955_p4[2] == 1'b1) begin
        l_fu_965_p3 = 32'd2;
    end else if (p_Result_5_fu_955_p4[3] == 1'b1) begin
        l_fu_965_p3 = 32'd3;
    end else if (p_Result_5_fu_955_p4[4] == 1'b1) begin
        l_fu_965_p3 = 32'd4;
    end else if (p_Result_5_fu_955_p4[5] == 1'b1) begin
        l_fu_965_p3 = 32'd5;
    end else if (p_Result_5_fu_955_p4[6] == 1'b1) begin
        l_fu_965_p3 = 32'd6;
    end else if (p_Result_5_fu_955_p4[7] == 1'b1) begin
        l_fu_965_p3 = 32'd7;
    end else if (p_Result_5_fu_955_p4[8] == 1'b1) begin
        l_fu_965_p3 = 32'd8;
    end else if (p_Result_5_fu_955_p4[9] == 1'b1) begin
        l_fu_965_p3 = 32'd9;
    end else if (p_Result_5_fu_955_p4[10] == 1'b1) begin
        l_fu_965_p3 = 32'd10;
    end else if (p_Result_5_fu_955_p4[11] == 1'b1) begin
        l_fu_965_p3 = 32'd11;
    end else if (p_Result_5_fu_955_p4[12] == 1'b1) begin
        l_fu_965_p3 = 32'd12;
    end else if (p_Result_5_fu_955_p4[13] == 1'b1) begin
        l_fu_965_p3 = 32'd13;
    end else if (p_Result_5_fu_955_p4[14] == 1'b1) begin
        l_fu_965_p3 = 32'd14;
    end else if (p_Result_5_fu_955_p4[15] == 1'b1) begin
        l_fu_965_p3 = 32'd15;
    end else if (p_Result_5_fu_955_p4[16] == 1'b1) begin
        l_fu_965_p3 = 32'd16;
    end else if (p_Result_5_fu_955_p4[17] == 1'b1) begin
        l_fu_965_p3 = 32'd17;
    end else if (p_Result_5_fu_955_p4[18] == 1'b1) begin
        l_fu_965_p3 = 32'd18;
    end else if (p_Result_5_fu_955_p4[19] == 1'b1) begin
        l_fu_965_p3 = 32'd19;
    end else if (p_Result_5_fu_955_p4[20] == 1'b1) begin
        l_fu_965_p3 = 32'd20;
    end else if (p_Result_5_fu_955_p4[21] == 1'b1) begin
        l_fu_965_p3 = 32'd21;
    end else if (p_Result_5_fu_955_p4[22] == 1'b1) begin
        l_fu_965_p3 = 32'd22;
    end else if (p_Result_5_fu_955_p4[23] == 1'b1) begin
        l_fu_965_p3 = 32'd23;
    end else if (p_Result_5_fu_955_p4[24] == 1'b1) begin
        l_fu_965_p3 = 32'd24;
    end else if (p_Result_5_fu_955_p4[25] == 1'b1) begin
        l_fu_965_p3 = 32'd25;
    end else if (p_Result_5_fu_955_p4[26] == 1'b1) begin
        l_fu_965_p3 = 32'd26;
    end else if (p_Result_5_fu_955_p4[27] == 1'b1) begin
        l_fu_965_p3 = 32'd27;
    end else if (p_Result_5_fu_955_p4[28] == 1'b1) begin
        l_fu_965_p3 = 32'd28;
    end else if (p_Result_5_fu_955_p4[29] == 1'b1) begin
        l_fu_965_p3 = 32'd29;
    end else if (p_Result_5_fu_955_p4[30] == 1'b1) begin
        l_fu_965_p3 = 32'd30;
    end else if (p_Result_5_fu_955_p4[31] == 1'b1) begin
        l_fu_965_p3 = 32'd31;
    end else begin
        l_fu_965_p3 = 32'd32;
    end
end

assign lsb_index_fu_979_p2 = ($signed(sub_ln894_fu_973_p2) + $signed(32'd4294967243));

assign lshr_ln198_1_fu_1427_p4 = {{add_ln198_1_fu_1421_p2[15:13]}};

assign lshr_ln198_2_fu_1484_p4 = {{add_ln198_2_fu_1479_p2[15:13]}};

assign lshr_ln198_3_fu_1530_p4 = {{add_ln198_3_fu_1525_p2[15:13]}};

assign lshr_ln198_4_fu_1586_p4 = {{add_ln198_4_fu_1581_p2[15:13]}};

assign lshr_ln198_5_fu_1632_p4 = {{add_ln198_5_fu_1627_p2[15:13]}};

assign lshr_ln198_6_fu_1688_p4 = {{add_ln198_6_fu_1683_p2[15:13]}};

assign lshr_ln198_7_fu_1734_p4 = {{add_ln198_7_fu_1729_p2[15:13]}};

assign lshr_ln1_fu_1378_p4 = {{add_ln198_fu_1372_p2[15:13]}};

assign lshr_ln897_fu_1015_p2 = 32'd4294967295 >> zext_ln897_fu_1011_p1;

assign lshr_ln908_fu_1126_p2 = zext_ln909_1_fu_1099_p1 >> zext_ln908_fu_1122_p1;

assign lshr_ln_fu_1269_p4 = {{add_ln174_fu_1263_p2[15:13]}};

assign m_2_fu_1142_p2 = (m_fu_1132_p3 + zext_ln911_fu_1139_p1);

assign m_5_fu_947_p3 = ((p_Result_4_fu_933_p3[0:0] == 1'b1) ? tmp_V_fu_941_p2 : start_value_V_fu_230);

assign m_6_fu_1148_p4 = {{m_2_fu_1142_p2[63:1]}};

assign m_fu_1132_p3 = ((icmp_ln908_reg_2329[0:0] == 1'b1) ? lshr_ln908_fu_1126_p2 : shl_ln909_fu_1111_p2);

assign mul_ln1148_1_fu_636_p0 = mul_ln1148_1_fu_636_p00;

assign mul_ln1148_1_fu_636_p00 = mul_ln1148_reg_2201;

assign mul_ln1148_1_fu_636_p1 = 141'd1888946593147858085479;

assign mul_ln1148_fu_627_p0 = mul_ln1148_fu_627_p00;

assign mul_ln1148_fu_627_p00 = ret_V_fu_617_p2;

assign mul_ln1148_fu_627_p1 = 70'd30786216525824;

assign num_points_address1 = grp_p_find_boundaries_and_starting_index_and_value4_fu_549_num_points_address1;

assign or_ln1506_fu_1235_p2 = (icmp_ln1506_reg_2349 | icmp_ln1506_1_reg_2354);

assign or_ln206_10_fu_831_p2 = (tmp_fu_669_p3 | 7'd11);

assign or_ln206_11_fu_846_p2 = (tmp_fu_669_p3 | 7'd12);

assign or_ln206_12_fu_861_p2 = (tmp_fu_669_p3 | 7'd13);

assign or_ln206_13_fu_876_p2 = (tmp_fu_669_p3 | 7'd14);

assign or_ln206_14_fu_891_p2 = (tmp_fu_669_p3 | 7'd15);

assign or_ln206_1_fu_696_p2 = (tmp_fu_669_p3 | 7'd2);

assign or_ln206_2_fu_711_p2 = (tmp_fu_669_p3 | 7'd3);

assign or_ln206_3_fu_726_p2 = (tmp_fu_669_p3 | 7'd4);

assign or_ln206_4_fu_741_p2 = (tmp_fu_669_p3 | 7'd5);

assign or_ln206_5_fu_756_p2 = (tmp_fu_669_p3 | 7'd6);

assign or_ln206_6_fu_771_p2 = (tmp_fu_669_p3 | 7'd7);

assign or_ln206_7_fu_786_p2 = (tmp_fu_669_p3 | 7'd8);

assign or_ln206_8_fu_801_p2 = (tmp_fu_669_p3 | 7'd9);

assign or_ln206_9_fu_816_p2 = (tmp_fu_669_p3 | 7'd10);

assign or_ln206_fu_681_p2 = (tmp_fu_669_p3 | 7'd1);

assign or_ln899_1_fu_1027_p2 = (shl_ln899_fu_1021_p2 | lshr_ln897_fu_1015_p2);

assign p_Result_4_fu_933_p3 = start_value_V_fu_230[32'd31];

integer ap_tvar_int_0;

always @ (m_5_fu_947_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_5_fu_955_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_5_fu_955_p4[ap_tvar_int_0] = m_5_fu_947_p3[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_6_fu_1059_p3 = m_5_fu_947_p3[lsb_index_fu_979_p2];

assign p_Result_7_fu_1196_p5 = {{tmp_1_fu_1189_p3}, {zext_ln912_fu_1158_p1[51:0]}};

assign p_Result_s_fu_1162_p3 = m_2_fu_1142_p2[32'd54];

assign ret_10_fu_1790_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4090));

assign ret_11_fu_1818_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4091));

assign ret_12_fu_1846_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4092));

assign ret_13_fu_1874_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4093));

assign ret_14_fu_1902_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4094));

assign ret_15_fu_1930_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4095));

assign ret_16_fu_1324_p1 = ap_phi_mux_lhs_1_phi_fu_539_p8[11:0];

assign ret_2_fu_1407_p2 = ($signed(ret_16_fu_1324_p1) + $signed(12'd4082));

assign ret_3_fu_1466_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4083));

assign ret_4_fu_1512_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4084));

assign ret_5_fu_1568_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4085));

assign ret_6_fu_1614_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4086));

assign ret_7_fu_1670_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4087));

assign ret_8_fu_1716_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4088));

assign ret_9_fu_1762_p2 = ($signed(ret_16_reg_2368) + $signed(12'd4089));

assign ret_V_1_fu_652_p2 = (trunc_ln_fu_642_p4 + 46'd24189364862976);

assign ret_V_fu_617_p2 = ($signed(y_V_fu_609_p3) + $signed(25'd28311552));

assign ret_fu_1328_p2 = ($signed(sext_ln215_fu_1320_p1) + $signed(33'd8589934577));

assign select_ln893_fu_1170_p3 = ((p_Result_s_fu_1162_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln896_fu_1079_p3 = ((icmp_ln896_fu_995_p2[0:0] == 1'b1) ? icmp_ln899_fu_1039_p2 : p_Result_6_fu_1059_p3);

assign select_ln908_fu_1087_p3 = ((icmp_ln908_fu_1067_p2[0:0] == 1'b1) ? select_ln896_fu_1079_p3 : and_ln899_1_fu_1073_p2);

assign sext_ln215_fu_1320_p1 = ap_phi_mux_lhs_1_phi_fu_539_p8;

assign sext_ln878_fu_1337_p1 = $signed(left_bound_V_fu_234);

assign shl_ln174_1_fu_1255_p3 = {{trunc_ln174_fu_1252_p1}, {4'd0}};

assign shl_ln198_10_fu_1823_p3 = {{ret_11_fu_1818_p2}, {4'd0}};

assign shl_ln198_11_fu_1851_p3 = {{ret_12_fu_1846_p2}, {4'd0}};

assign shl_ln198_12_fu_1879_p3 = {{ret_13_fu_1874_p2}, {4'd0}};

assign shl_ln198_13_fu_1907_p3 = {{ret_14_fu_1902_p2}, {4'd0}};

assign shl_ln198_14_fu_1935_p3 = {{ret_15_fu_1930_p2}, {4'd0}};

assign shl_ln198_15_fu_1958_p3 = {{ret_16_reg_2368}, {4'd0}};

assign shl_ln198_1_fu_1364_p3 = {{add_ln1461_fu_1351_p2}, {4'd0}};

assign shl_ln198_2_fu_1413_p3 = {{ret_2_fu_1407_p2}, {4'd0}};

assign shl_ln198_3_fu_1471_p3 = {{ret_3_fu_1466_p2}, {4'd0}};

assign shl_ln198_4_fu_1517_p3 = {{ret_4_fu_1512_p2}, {4'd0}};

assign shl_ln198_5_fu_1573_p3 = {{ret_5_fu_1568_p2}, {4'd0}};

assign shl_ln198_6_fu_1619_p3 = {{ret_6_fu_1614_p2}, {4'd0}};

assign shl_ln198_7_fu_1675_p3 = {{ret_7_fu_1670_p2}, {4'd0}};

assign shl_ln198_8_fu_1721_p3 = {{ret_8_fu_1716_p2}, {4'd0}};

assign shl_ln198_9_fu_1767_p3 = {{ret_9_fu_1762_p2}, {4'd0}};

assign shl_ln198_s_fu_1795_p3 = {{ret_10_fu_1790_p2}, {4'd0}};

assign shl_ln1_fu_1357_p3 = {{i_offset}, {13'd0}};

assign shl_ln899_fu_1021_p2 = 32'd1 << lsb_index_fu_979_p2;

assign shl_ln909_fu_1111_p2 = zext_ln909_1_fu_1099_p1 << zext_ln909_fu_1107_p1;

assign shl_ln_fu_1245_p3 = {{i_offset}, {13'd0}};

assign start_index_V_1_fu_1299_p2 = (start_index_V_fu_226 + 32'd1);

assign start_value_V_1_fu_1310_p2 = (z_bits_fu_1295_p1 - zext_ln708_reg_2297);

assign sub_ln894_fu_973_p2 = (32'd32 - l_fu_965_p3);

assign sub_ln897_fu_1005_p2 = (6'd22 - trunc_ln897_fu_1001_p1);

assign sub_ln909_fu_1102_p2 = (32'd54 - sub_ln894_reg_2323);

assign sub_ln915_fu_1178_p2 = (11'd12 - trunc_ln893_reg_2339);

assign temp_superpoint_V_10_fu_2068_p1 = points_q0[95:0];

assign temp_superpoint_V_11_fu_2073_p1 = points_q1[95:0];

assign temp_superpoint_V_12_fu_2112_p1 = points_q0[95:0];

assign temp_superpoint_V_13_fu_2117_p1 = points_q1[95:0];

assign temp_superpoint_V_14_fu_2150_p1 = points_q0[95:0];

assign temp_superpoint_V_15_fu_2155_p1 = points_q1[95:0];

assign temp_superpoint_V_1_fu_1461_p1 = points_q0[95:0];

assign temp_superpoint_V_2_fu_1558_p1 = points_q0[95:0];

assign temp_superpoint_V_3_fu_1563_p1 = points_q1[95:0];

assign temp_superpoint_V_4_fu_1660_p1 = points_q0[95:0];

assign temp_superpoint_V_5_fu_1665_p1 = points_q1[95:0];

assign temp_superpoint_V_6_fu_1980_p1 = points_q0[95:0];

assign temp_superpoint_V_7_fu_1985_p1 = points_q1[95:0];

assign temp_superpoint_V_8_fu_2024_p1 = points_q0[95:0];

assign temp_superpoint_V_9_fu_2029_p1 = points_q1[95:0];

assign temp_superpoint_V_fu_1456_p1 = points_q1[95:0];

assign tmp_10_fu_807_p3 = {{57'd0}, {or_ln206_8_fu_801_p2}};

assign tmp_11_fu_822_p3 = {{57'd0}, {or_ln206_9_fu_816_p2}};

assign tmp_12_fu_837_p3 = {{57'd0}, {or_ln206_10_fu_831_p2}};

assign tmp_13_fu_852_p3 = {{57'd0}, {or_ln206_11_fu_846_p2}};

assign tmp_14_fu_867_p3 = {{57'd0}, {or_ln206_12_fu_861_p2}};

assign tmp_15_fu_882_p3 = {{57'd0}, {or_ln206_13_fu_876_p2}};

assign tmp_16_fu_897_p3 = {{57'd0}, {or_ln206_14_fu_891_p2}};

assign tmp_18_fu_1282_p3 = {{lshr_ln_fu_1269_p4}, {trunc_ln174_1_fu_1279_p1}};

assign tmp_19_fu_985_p4 = {{lsb_index_fu_979_p2[31:1]}};

assign tmp_1_fu_1189_p3 = {{p_Result_4_reg_2313}, {add_ln915_fu_1183_p2}};

assign tmp_20_fu_1045_p3 = lsb_index_fu_979_p2[32'd31];

assign tmp_21_fu_1394_p3 = {{lshr_ln1_fu_1378_p4}, {add_ln198_16_fu_1388_p2}};

assign tmp_22_fu_1443_p3 = {{lshr_ln198_1_fu_1427_p4}, {add_ln198_17_fu_1437_p2}};

assign tmp_23_fu_1499_p3 = {{lshr_ln198_2_fu_1484_p4}, {add_ln198_18_fu_1494_p2}};

assign tmp_24_fu_1545_p3 = {{lshr_ln198_3_fu_1530_p4}, {add_ln198_19_fu_1540_p2}};

assign tmp_25_fu_1601_p3 = {{lshr_ln198_4_fu_1586_p4}, {add_ln198_20_fu_1596_p2}};

assign tmp_26_fu_1647_p3 = {{lshr_ln198_5_fu_1632_p4}, {add_ln198_21_fu_1642_p2}};

assign tmp_27_fu_1703_p3 = {{lshr_ln198_6_fu_1688_p4}, {add_ln198_22_fu_1698_p2}};

assign tmp_28_fu_1749_p3 = {{lshr_ln198_7_fu_1734_p4}, {add_ln198_23_fu_1744_p2}};

assign tmp_29_fu_1995_p3 = {{lshr_ln198_8_reg_2466}, {add_ln198_24_fu_1990_p2}};

assign tmp_30_fu_2012_p3 = {{lshr_ln198_9_reg_2471}, {add_ln198_25_fu_2007_p2}};

assign tmp_31_fu_2039_p3 = {{lshr_ln198_s_reg_2476}, {add_ln198_26_fu_2034_p2}};

assign tmp_32_fu_2056_p3 = {{lshr_ln198_10_reg_2481}, {add_ln198_27_fu_2051_p2}};

assign tmp_33_fu_2083_p3 = {{lshr_ln198_11_reg_2486}, {add_ln198_28_fu_2078_p2}};

assign tmp_34_fu_2100_p3 = {{lshr_ln198_12_reg_2491}, {add_ln198_29_fu_2095_p2}};

assign tmp_35_fu_2127_p3 = {{lshr_ln198_13_reg_2496}, {add_ln198_30_fu_2122_p2}};

assign tmp_36_fu_2139_p3 = {{lshr_ln198_14_reg_2501}, {trunc_ln1461_reg_2390}};

assign tmp_3_fu_687_p3 = {{57'd0}, {or_ln206_fu_681_p2}};

assign tmp_4_fu_702_p3 = {{57'd0}, {or_ln206_1_fu_696_p2}};

assign tmp_5_fu_717_p3 = {{57'd0}, {or_ln206_2_fu_711_p2}};

assign tmp_6_fu_732_p3 = {{57'd0}, {or_ln206_3_fu_726_p2}};

assign tmp_7_fu_747_p3 = {{57'd0}, {or_ln206_4_fu_741_p2}};

assign tmp_8_fu_762_p3 = {{57'd0}, {or_ln206_5_fu_756_p2}};

assign tmp_9_fu_777_p3 = {{57'd0}, {or_ln206_6_fu_771_p2}};

assign tmp_V_fu_941_p2 = (32'd0 - start_value_V_fu_230);

assign tmp_fu_669_p3 = {{i_offset}, {4'd0}};

assign tmp_s_fu_792_p3 = {{57'd0}, {or_ln206_7_fu_786_p2}};

assign trunc_ln1461_fu_1347_p1 = ap_phi_mux_lhs_1_phi_fu_539_p8[8:0];

assign trunc_ln174_1_fu_1279_p1 = start_index_V_fu_226[8:0];

assign trunc_ln174_fu_1252_p1 = start_index_V_fu_226[11:0];

assign trunc_ln3_fu_1213_p4 = {{m_2_fu_1142_p2[52:1]}};

assign trunc_ln731_fu_605_p1 = get_radiiradii_q0[4:0];

assign trunc_ln893_fu_1095_p1 = l_fu_965_p3[10:0];

assign trunc_ln897_fu_1001_p1 = sub_ln894_fu_973_p2[5:0];

assign trunc_ln_fu_642_p4 = {{mul_ln1148_1_fu_636_p2[140:95]}};

assign xor_ln899_fu_1053_p2 = (tmp_20_fu_1045_p3 ^ 1'd1);

assign y_V_fu_609_p3 = {{trunc_ln731_fu_605_p1}, {20'd0}};

assign z_bits_fu_1295_p1 = points_q0[31:0];

assign zext_ln174_fu_1290_p1 = tmp_18_fu_1282_p3;

assign zext_ln198_10_fu_2046_p1 = tmp_31_fu_2039_p3;

assign zext_ln198_11_fu_2063_p1 = tmp_32_fu_2056_p3;

assign zext_ln198_12_fu_2090_p1 = tmp_33_fu_2083_p3;

assign zext_ln198_13_fu_2107_p1 = tmp_34_fu_2100_p3;

assign zext_ln198_14_fu_2134_p1 = tmp_35_fu_2127_p3;

assign zext_ln198_15_fu_2145_p1 = tmp_36_fu_2139_p3;

assign zext_ln198_1_fu_1451_p1 = tmp_22_fu_1443_p3;

assign zext_ln198_2_fu_1507_p1 = tmp_23_fu_1499_p3;

assign zext_ln198_3_fu_1553_p1 = tmp_24_fu_1545_p3;

assign zext_ln198_4_fu_1609_p1 = tmp_25_fu_1601_p3;

assign zext_ln198_5_fu_1655_p1 = tmp_26_fu_1647_p3;

assign zext_ln198_6_fu_1711_p1 = tmp_27_fu_1703_p3;

assign zext_ln198_7_fu_1757_p1 = tmp_28_fu_1749_p3;

assign zext_ln198_8_fu_2002_p1 = tmp_29_fu_1995_p3;

assign zext_ln198_9_fu_2019_p1 = tmp_30_fu_2012_p3;

assign zext_ln198_fu_1402_p1 = tmp_21_fu_1394_p3;

assign zext_ln206_fu_676_p1 = tmp_fu_669_p3;

assign zext_ln708_fu_906_p1 = projectionToRow_V_reg_2206;

assign zext_ln84_fu_573_p1 = i_offset;

assign zext_ln897_fu_1011_p1 = sub_ln897_fu_1005_p2;

assign zext_ln908_fu_1122_p1 = add_ln908_fu_1117_p2;

assign zext_ln909_1_fu_1099_p1 = m_5_reg_2318;

assign zext_ln909_fu_1107_p1 = sub_ln909_fu_1102_p2;

assign zext_ln911_fu_1139_p1 = select_ln908_reg_2334;

assign zext_ln912_fu_1158_p1 = m_6_fu_1148_p4;

always @ (posedge ap_clk) begin
    zext_ln84_reg_2191[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    init_patch_addr_reg_2217[3:0] <= 4'b0000;
    init_patch_addr_1_reg_2222[3:0] <= 4'b0001;
    init_patch_addr_2_reg_2227[3:0] <= 4'b0010;
    init_patch_addr_3_reg_2232[3:0] <= 4'b0011;
    init_patch_addr_4_reg_2237[3:0] <= 4'b0100;
    init_patch_addr_5_reg_2242[3:0] <= 4'b0101;
    init_patch_addr_6_reg_2247[3:0] <= 4'b0110;
    init_patch_addr_7_reg_2252[3:0] <= 4'b0111;
    init_patch_addr_8_reg_2257[3:0] <= 4'b1000;
    init_patch_addr_9_reg_2262[3:0] <= 4'b1001;
    init_patch_addr_10_reg_2267[3:0] <= 4'b1010;
    init_patch_addr_11_reg_2272[3:0] <= 4'b1011;
    init_patch_addr_12_reg_2277[3:0] <= 4'b1100;
    init_patch_addr_13_reg_2282[3:0] <= 4'b1101;
    init_patch_addr_14_reg_2287[3:0] <= 4'b1110;
    init_patch_addr_15_reg_2292[3:0] <= 4'b1111;
    zext_ln708_reg_2297[31:26] <= 6'b000000;
    shl_ln1_reg_2408[12:0] <= 13'b0000000000000;
end

endmodule //system_top_alignedtoline_per_layer_loop3
